spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
custom:
  temp:
    dirPath: c:/temp/slog_test/temp
  genFile:
    dirPath: c:/temp/slog_test